name: 0db.tv
favicon: null
layout_spectrum: 0.0971272811293602
typography_spectrum: 0.861776898149401
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7e8ec'
    - '#a29d9a'
    - '#756b69'
    - '#2f2f31'
    - '#6c101d'
  brandStrength: 0.16180338780395687
  lightness: 0.6095937446225435
  saturation: 0.058015283197164536
  rhythmicContrast: 0.25826411903835833
purpose: []
