name: 0db.tv
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8994
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7e8ec'
    - '#a29d9a'
    - '#756b69'
    - '#2f2f31'
    - '#6c101d'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
